In [40]:
!pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [42]:
import pandas as pd

df = pd.read_excel("SaleReport_10_08_24_to_30_06_26.xlsx")
df.head()

df1 = pd.read_excel("Sale_Report_01-04-2021_to_08-08-2024.xls")
df1.head()
# Combine both files
df = pd.concat([df, df1], ignore_index=True)

# Remove duplicate rows
df = df.drop_duplicates()

print("Total Rows:", len(df))

Total Rows: 80011

In [82]:

# Convert Date
df['Date'] = pd.to_datetime(
    df['Date'],
    dayfirst=True
)


# Create Year and Month columns
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
monthly = (
    df.groupby(['Year', 'Month', 'Item Name'], as_index=False)
      .agg(
          Quantity=('Quantity', 'sum'),
          Amount=('Amount', 'sum')
      )
)

print(monthly.shape)
monthly.to_excel("Monthly_Product_Sales.xlsx", index=False)

(13595, 5)

In [83]:
print(monthly.columns.tolist())

['Year', 'Month', 'Item Name', 'Quantity', 'Amount']

In [84]:
print(df['Item Name'].nunique())
print(df['Item Name'].unique())

1461
['Safal (Tropical) 1Ltr' 'Copper Sulphate 1Kg' 'H-Lime (Vanita) 400gm' ...
 'Guwar Chowli Jawari (Mrityunjay) 50gm' 'Biozyme (Biostadt) 100ml'
 'Ignite (Biostadt) 500gm']

In [47]:
print("Total rows:", len(df))

Total rows: 80011

In [85]:
print(df['Month'].unique())
print("Number of months:", df['Month'].nunique())

[ 8  9 10 11 12  1  2  3  4  5  6  7]
Number of months: 12

In [86]:
monthly.head()

   Year  Month                   Item Name  Quantity   Amount
0  2022      9     0-0-50 (Greenfield) 1Kg      36.0   4320.0
1  2022      9    0-52-34 (Greenfield) 1Kg      78.0  12490.0
2  2022      9         00-00-50 (ICL) 25Kg       3.0   9300.0
3  2022      9  00-52-34 (Greenfield) 25Kg       1.0   3550.0
4  2022      9   12-61-00 (Greenfield) 1Kg      23.0   2990.0

In [87]:
monthly.tail()

       Year  Month                    Item Name  Quantity  Amount
13590  2026      6         Z-78 (Indofil) 500gm       9.0  3150.0
13591  2026      6  Z-SILICON (NUTRIXEAL) 500GM       8.0  2520.0
13592  2026      6     Zinc Sulphate (GCCI) 1Kg       7.0  1400.0
13593  2026      6  Zinc Sulphate (Nature) 10Kg       1.0   850.0
13594  2026      6                          mel       1.0     0.0

In [88]:
print(df.shape)
print(df['Item Name'].nunique())
print(df['Item Name'].head(10))

(80011, 23)
1461
0         Safal (Tropical) 1Ltr
1           Copper Sulphate 1Kg
2         H-Lime (Vanita) 400gm
3       Cabrio Top (BASF) 300gm
4             Urea (Kisan) 45Kg
5             Urea (Kisan) 45Kg
6      TAG SAF (Tropical) 115ml
7       TAGTAF (Tropical) 500gm
8         Contaf (Rallis) 250ml
9    Tag Start (Tropical) 100gm
Name: Item Name, dtype: object

In [52]:
print(monthly.shape)
print(monthly['Item Name'].nunique())

(13595, 5)
1461

In [89]:
print(df['Item Code'].isna().sum())
print(df['Item Code'].notna().sum())

79947
64

In [90]:
monthly.head()

   Year  Month                   Item Name  Quantity   Amount
0  2022      9     0-0-50 (Greenfield) 1Kg      36.0   4320.0
1  2022      9    0-52-34 (Greenfield) 1Kg      78.0  12490.0
2  2022      9         00-00-50 (ICL) 25Kg       3.0   9300.0
3  2022      9  00-52-34 (Greenfield) 25Kg       1.0   3550.0
4  2022      9   12-61-00 (Greenfield) 1Kg      23.0   2990.0

monthly['Rolling3'] = (
    monthly.groupby('Item Name')['Quantity']
           .transform(lambda x: x.shift(1).rolling(3).mean())
)

monthly['Rolling6'] = (
    monthly.groupby('Item Name')['Quantity']
           .transform(lambda x: x.shift(1).rolling(6).mean())
)

In [91]:
monthly.fillna(0, inplace=True)

In [92]:
monthly.head()

   Year  Month                   Item Name  Quantity   Amount
0  2022      9     0-0-50 (Greenfield) 1Kg      36.0   4320.0
1  2022      9    0-52-34 (Greenfield) 1Kg      78.0  12490.0
2  2022      9         00-00-50 (ICL) 25Kg       3.0   9300.0
3  2022      9  00-52-34 (Greenfield) 25Kg       1.0   3550.0
4  2022      9   12-61-00 (Greenfield) 1Kg      23.0   2990.0

In [93]:
monthly.tail()

       Year  Month                    Item Name  Quantity  Amount
13590  2026      6         Z-78 (Indofil) 500gm       9.0  3150.0
13591  2026      6  Z-SILICON (NUTRIXEAL) 500GM       8.0  2520.0
13592  2026      6     Zinc Sulphate (GCCI) 1Kg       7.0  1400.0
13593  2026      6  Zinc Sulphate (Nature) 10Kg       1.0   850.0
13594  2026      6                          mel       1.0     0.0

In [94]:
monthly_40 = monthly[monthly['Quantity'] > 40]

print(monthly_40.shape)
monthly_40.head()

(641, 5)

     Year  Month                  Item Name  Quantity    Amount
1    2022      9   0-52-34 (Greenfield) 1Kg      78.0  12490.00
7    2022      9  19-19-19 (Greenfield) 1Kg      99.0  11850.00
40   2022      9      Boom Flower (JS) 1Ltr      42.0   9810.00
91   2022      9               H-Lime 400gm      77.0   1540.00
141  2022      9   Raiper (Jai Kisan) 100gm      61.0  13969.99

In [95]:
monthly_40.to_excel("Monthly_Product_Sales_Qty_GT_40.xlsx", index=False)

In [96]:
monthly_40.head()

     Year  Month                  Item Name  Quantity    Amount
1    2022      9   0-52-34 (Greenfield) 1Kg      78.0  12490.00
7    2022      9  19-19-19 (Greenfield) 1Kg      99.0  11850.00
40   2022      9      Boom Flower (JS) 1Ltr      42.0   9810.00
91   2022      9               H-Lime 400gm      77.0   1540.00
141  2022      9   Raiper (Jai Kisan) 100gm      61.0  13969.99

In [97]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

monthly['ProductID'] = le.fit_transform(monthly['Item Name'])

In [98]:
import joblib

joblib.dump(le, "product_encoder.pkl")

['product_encoder.pkl']

In [100]:
X = monthly[
    [
        'ProductID',
        'Year',
        'Month'
    ]
]

y = monthly['Quantity']

In [101]:
train = monthly[monthly['Year'] <= 2025]
test = monthly[monthly['Year'] == 2026]

X_train = train[X.columns]
y_train = train['Quantity']

X_test = test[X.columns]
y_test = test['Quantity']

In [72]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in C:\Automation\Lib\site-packages (from catboost) (3.10.7)
Requirement already satisfied: numpy<3.0,>=1.16.0 in C:\Automation\Lib\site-packages (from catboost) (2.3.4)
Requirement already satisfied: pandas<4.0,>=0.24 in C:\Automation\Lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in C:\Automation\Lib\site-packages (from catboost) (1.16.3)
Collecting plotly (from catboost)
  Downloading plotly-6.8.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: six in C:\Automation\Lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Automation\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Automation\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Automation\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (12.0.0)
Requirement already satisfied: pyparsing>=3 in C:\Automation\Lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in C:\Automation\Lib\site-packages (from plotly->catboost) (2.17.0)
Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
    --------------------------------------- 1.8/100.2 MB 14.6 MB/s eta 0:00:07
   - -------------------------------------- 4.7/100.2 MB 14.7 MB/s eta 0:00:07
   --- ------------------------------------ 7.9/100.2 MB 14.8 MB/s eta 0:00:07
   ---- ----------------------------------- 11.0/100.2 MB 14.8 MB/s eta 0:00:07
   ----- ---------------------------------- 13.9/100.2 MB 14.8 MB/s eta 0:00:06
   ------ --------------------------------- 16.8/100.2 MB 14.7 MB/s eta 0:00:06
   ------- -------------------------------- 19.9/100.2 MB 14.7 MB/s eta 0:00:06
   --------- ------------------------------ 22.8/100.2 MB 14.6 MB/s eta 0:00:06
   ---------- ----------------------------- 25.7/100.2 MB 14.7 MB/s eta 0:00:06
   ----------- ---------------------------- 28.8/100.2 MB 14.7 MB/s eta 0:00:05
   ------------ --------------------------- 32.0/100.2 MB 14.7 MB/s eta 0:00:05
   ------------- -------------------------- 34.9/100.2 MB 14.6 MB/s eta 0:00:05
   --------------- ------------------------ 38.0/100.2 MB 14.7 MB/s eta 0:00:05
   ---------------- ----------------------- 40.9/100.2 MB 14.6 MB/s eta 0:00:05
   ----------------- ---------------------- 44.0/100.2 MB 14.6 MB/s eta 0:00:04
   ------------------ --------------------- 46.9/100.2 MB 14.6 MB/s eta 0:00:04
   ------------------- -------------------- 49.8/100.2 MB 14.6 MB/s eta 0:00:04
   --------------------- ------------------ 52.7/100.2 MB 14.5 MB/s eta 0:00:04
   ---------------------- ----------------- 55.6/100.2 MB 14.5 MB/s eta 0:00:04
   ----------------------- ---------------- 58.5/100.2 MB 14.4 MB/s eta 0:00:03
   ------------------------ --------------- 61.3/100.2 MB 14.4 MB/s eta 0:00:03
   ------------------------- -------------- 64.5/100.2 MB 14.5 MB/s eta 0:00:03
   -------------------------- ------------- 67.4/100.2 MB 14.5 MB/s eta 0:00:03
   ---------------------------- ----------- 70.5/100.2 MB 14.5 MB/s eta 0:00:03
   ----------------------------- ---------- 73.7/100.2 MB 14.5 MB/s eta 0:00:02
   ------------------------------ --------- 76.5/100.2 MB 14.5 MB/s eta 0:00:02
   ------------------------------- -------- 79.7/100.2 MB 14.5 MB/s eta 0:00:02
   -------------------------------- ------- 82.6/100.2 MB 14.5 MB/s eta 0:00:02
   ---------------------------------- ----- 85.7/100.2 MB 14.5 MB/s eta 0:00:01
   ----------------------------------- ---- 88.6/100.2 MB 14.5 MB/s eta 0:00:01
   ------------------------------------ --- 91.8/100.2 MB 14.5 MB/s eta 0:00:01
   ------------------------------------- -- 94.6/100.2 MB 14.5 MB/s eta 0:00:01
   -------------------------------------- - 97.5/100.2 MB 14.5 MB/s eta 0:00:01
   --------------------------------------  100.1/100.2 MB 14.5 MB/s eta 0:00:01
   --------------------------------------  100.1/100.2 MB 14.5 MB/s eta 0:00:01
   ---------------------------------------- 100.2/100.2 MB 13.8 MB/s  0:00:07
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Downloading plotly-6.8.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ----------- ---------------------------- 2.9/9.9 MB 14.7 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.9 MB 15.2 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 15.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 14.0 MB/s  0:00:00
Installing collected packages: plotly, graphviz, catboost

   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ------------- -------------------------- 1/3 [graphviz]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   ---------------------------------------- 3/3 [catboost]

Successfully installed catboost-1.2.10 graphviz-0.21 plotly-6.8.0

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [74]:
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

In [102]:
rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)

rf.fit(X_train,y_train)

RandomForestRegressor(n_estimators=300, random_state=42)

In [103]:
xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

xgb.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [104]:
cat = CatBoostRegressor(verbose=False)

cat.fit(X_train,y_train)

CatBoostRegressor(loss_function='RMSE', verbose=False)

In [105]:
from sklearn.metrics import mean_absolute_error
import numpy as np

models = {
    "RF": rf,
    "XGB": xgb,
    "CAT": cat
}

for name, model in models.items():

    pred = model.predict(X_test)

    mae = mean_absolute_error(y_test,pred)

    rmse = np.sqrt(((y_test-pred)**2).mean())

    print(name,mae,rmse)

RF 6.819630972818312 21.756634968445375
XGB 7.33701744295101 25.78370952934656
CAT 7.331644866379738 21.046207258596702

In [106]:
import joblib

joblib.dump(xgb,"inventory_model.pkl")

['inventory_model.pkl']

In [78]:
import streamlit as st
import joblib

model = joblib.load("inventory_model.pkl")
encoder = joblib.load("product_encoder.pkl")

product = st.selectbox(
    "Product",
    encoder.classes_
)

year = st.number_input("Year",2026)

month = st.selectbox(
    "Month",
    list(range(1,13))
)

if st.button("Predict"):

    pid = encoder.transform([product])[0]

    X = [[
        pid,
        year,
        month
    ]]

    pred = model.predict(X)

    st.success(
        f"Required Inventory : {round(pred[0])}"
    )

2026-06-30 22:53:43.822 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:43.824 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:43.827 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:43.829 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:43.830 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2026-06-30 22:53:43.832 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.098
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Automation\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-06-30 22:53:44.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.105 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.107 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.110 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.115 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.117 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.123 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.124 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.125 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-30 22:53:44.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

SyntaxError: invalid syntax (601329205.py, line 1)